// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5901.hepa.commands;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc5901.hepa.Robot;
import org.usfirst.frc5901.hepa.RobotMap;

/**
 *
 */
public class AutonomousTurn extends Command {
	protected double angleTarget;
	double angle;
	double error;
	double error_sum=0;
	double kp_turn = 0.022; //.013 is good on concrete, .015 good carpet, .02 good for 65\
	double ki_turn = 0.005;


    public AutonomousTurn(double angleTarget) {
    	this.angleTarget = angleTarget;
    	requires(Robot.drivetrain);
    }

    // Called just before this Command runs the first time
    protected void initialize() {

    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
		angle = RobotMap.drivetrainGodRicardoGyro.getAngle(); 						// get current heading
		error = angleTarget - angle;
		error_sum += error;

		Robot.drivetrain.cougarDrive(0.0, error*kp_turn);		


    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drivetrain.stopDrive();	
    }
    
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	System.out.println("TURNING - Error Angle:" + error + " Target Angle:" + angle);
    }
}
